// GENERATED by scripts/gen-types.mjs from the server's tools/list — do not edit.
// Regenerate with `npm run gen:types`; test/types-generated.test.mjs fails on drift.
//
// Input types for every safari-mcp tool (98), for TypeScript MCP clients:
//   const args: SafariToolInput<"safari_navigate"> = { url: "https://example.com" };
//   await client.callTool({ name: "safari_navigate", arguments: args });

export type MCPContent =
  | { type: "text"; text: string }
  | { type: "image"; data: string; mimeType: string };

export interface MCPToolResult {
  content: MCPContent[];
  isError?: boolean;
}

export interface SafariToolInputs {
  /** Get the accessibility tree of the page (roles, ARIA labels, focusable elements, form states). Essential for a11y auditing. */
  safari_accessibility_snapshot: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** CSS selector for subtree (default: full page) */
    selector?: string;
    /** Max tree depth (default: 5) */
    maxDepth?: number;
  };
  /** Full page analysis in ONE call: title, URL, meta tags, OG, headings, link stats, image stats, forms, and text preview. Perfect for SEO/audit. */
  safari_analyze_page: Record<string, never>;
  /** Audit the page for iOS 'Add to Home Screen' / PWA readiness: apple-mobile-web-app-capable, apple-touch-icon (incl. 180x180), theme-color, status-bar style, web app manifest, splash screens. Returns a pass/total checklist. */
  safari_check_pwa: Record<string, never>;
  /** Clear all captured console messages */
  safari_clear_console: Record<string, never>;
  /** Clear an input field */
  safari_clear_field: {
    /** CSS selector of the input */
    selector: string;
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
  };
  /** Remove all network route mocks (restore real network behavior) */
  safari_clear_mocks: Record<string, never>;
  /** Clear all captured network requests */
  safari_clear_network: Record<string, never>;
  /** Click element. Use ref (from snapshot), selector, text, or x/y. Works on React/Airtable/virtual DOM apps via full PointerEvent+MouseEvent sequence + React Fiber fallback. Pure JS — never touches user's mouse. When using ref, always take a FRESH safari_snapshot first — refs expire after each new snapshot. */
  safari_click: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** Ref ID from safari_snapshot (e.g. '0_5') */
    ref?: string;
    /** CSS selector */
    selector?: string;
    /** Visible text to find and click */
    text?: string;
    /** X coordinate */
    x?: number;
    /** Y coordinate */
    y?: number;
  };
  /** Click an element then return the updated page — saves 1 full round-trip vs separate click+read_page. Handles both React Router navigation and full page loads. */
  safari_click_and_read: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** Visible text of the element to click */
    text?: string;
    /** CSS selector */
    selector?: string;
    /** X coordinate */
    x?: number;
    /** Y coordinate */
    y?: number;
    /** Ms to wait after click (default: auto-detect navigation) */
    wait?: number;
    /** Max chars to return (default: 50000) */
    maxLength?: number;
  };
  /** Click an element AND wait for the result (page load or element). Use instead of click + wait_for separately. */
  safari_click_and_wait: {
    /** CSS selector to click */
    selector?: string;
    /** Visible text to click */
    text?: string;
    /** CSS selector to wait for after click */
    waitFor?: string;
    /** Wait timeout in ms (default: 10000) */
    timeout?: number;
  };
  /** Read the current clipboard content (text) */
  safari_clipboard_read: Record<string, never>;
  /** Write text to the system clipboard */
  safari_clipboard_write: {
    /** Text to copy to clipboard */
    text: string;
  };
  /** Close the current tab. After a daemon/session restart, pass the opaque receipt returned by safari_new_tab or safari_list_tabs. */
  safari_close_tab: {
    /** Opaque extension-issued tab receipt */
    receipt?: string;
    /** Deprecated legacy receipt URL */
    url?: string;
  };
  /** Get console messages filtered by level (must call safari_start_console first) */
  safari_console_filter: {
    /** Console level to filter */
    level: "log" | "warn" | "error" | "info";
  };
  /** Analyze CSS coverage: find unused CSS rules across all stylesheets. Shows coverage percentage per stylesheet. */
  safari_css_coverage: Record<string, never>;
  /** Delete a specific cookie or all cookies for the current page */
  safari_delete_cookies: {
    /** Cookie name to delete */
    name?: string;
    /** Delete all cookies */
    all?: boolean;
  };
  /** Delete a localStorage key, or clear all localStorage (omit key to clear all) */
  safari_delete_local_storage: {
    /** Key to delete (omit to clear ALL) */
    key?: string;
  };
  /** Delete a sessionStorage key, or clear all sessionStorage (omit key to clear all) */
  safari_delete_session_storage: {
    /** Key to delete (omit to clear ALL) */
    key?: string;
  };
  /** Auto-detect all forms on the page with their fields, types, selectors, and submit buttons. Great for automated form filling. */
  safari_detect_forms: Record<string, never>;
  /** Diagnose the macOS permission + daemon chain in one shot: Safari running, Apple Events/Automation, native helper daemon, Accessibility (native clicks), Screen Recording, and the helper's codesign identity. Returns a pass/fail checklist with the exact System Settings fix per failure, then the extension bridge: which worker holds the profile lease, every worker that tried and what the profile probe answered it, and what each Safari profile's extension storage holds. Run this FIRST when clicks/screenshots/startup 'don't work even with permissions granted' or when tools answer 'profile extension unavailable'. */
  safari_doctor: Record<string, never>;
  /** Double-click an element by CSS selector or x/y coordinates (e.g. to select a word in text) */
  safari_double_click: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** CSS selector */
    selector?: string;
    /** X coordinate */
    x?: number;
    /** Y coordinate */
    y?: number;
  };
  /** Drag an element to another element or position. Use CSS selectors or x/y coordinates. */
  safari_drag: {
    /** CSS selector of element to drag */
    sourceSelector?: string;
    /** CSS selector of drop target */
    targetSelector?: string;
    /** Source X coordinate */
    sourceX?: number;
    /** Source Y coordinate */
    sourceY?: number;
    /** Target X coordinate */
    targetX?: number;
    /** Target Y coordinate */
    targetY?: number;
  };
  /** Emulate a mobile device: sizes the Safari window to the device's CSS viewport and overrides navigator.userAgent/platform/maxTouchPoints (iOS/iPadOS 27 values) in the current page — JavaScript only: the HTTP User-Agent header is unchanged and a reload or navigation clears it. Devices: iphone-18-pro, iphone-18-pro-max, iphone-air, iphone-17, iphone-17e, iphone-16, iphone-14, iphone-14-pro-max, ipad, ipad-air-11, ipad-air-13, ipad-pro-11, ipad-pro-13, ipad-pro, pixel-7, galaxy-s24. Or pass width/height (and userAgent). */
  safari_emulate: {
    /** Device name from the list in the description, e.g. iphone-18-pro, iphone-air, ipad-pro-11 */
    device?: string;
    /** Custom viewport width */
    width?: number;
    /** Custom viewport height */
    height?: number;
    /** Custom user agent string */
    userAgent?: string;
  };
  /** Execute JavaScript read from a FILE path (avoids passing huge scripts inline / manual copy). Same engine as safari_evaluate: extension-first (no focus steal), AppleScript fallback. Use to upload binary via a generated .js containing base64. */
  safari_eval_file: {
    /** Absolute path to a .js file whose contents are the script to execute */
    path: string;
  };
  /** Execute JavaScript in the current page (a returned Promise is awaited — fetch/timers work in background tabs; requestAnimationFrame never fires there). Automatically falls back to AppleScript when CSP blocks execution (e.g. Google Search Console, LinkedIn). For reading data, prefer safari_read_page or safari_snapshot. For interactions, prefer safari_click/fill with refs. */
  safari_evaluate: {
    /** JavaScript code to execute */
    script: string;
    /** Run inside a sub-frame instead of the main document: a frameId from safari_list_frames, or a substring of the frame's URL (must match exactly one). Needed for cross-origin iframes — micro-frontend app shells, embedded checkouts — where the main document only holds a loader. */
    frame?: string | number;
    /** Opaque extension-issued tab receipt — pass the one safari_new_tab returned to keep targeting that tab after an MCP reconnect */
    receipt?: string;
  };
  /** Export all storage state (cookies + localStorage + sessionStorage) as JSON — useful for saving and restoring login sessions */
  safari_export_storage: Record<string, never>;
  /** Extract all images with src, alt, dimensions, loading strategy, viewport visibility */
  safari_extract_images: {
    /** Max images (default: 50) */
    limit?: number;
  };
  /** Extract all links with href, text, rel, target, external/nofollow detection */
  safari_extract_links: {
    /** Max links (default: 100) */
    limit?: number;
    /** Filter by URL or text substring */
    filter?: string;
  };
  /** Extract all meta tags: title, description, canonical, OG tags, Twitter cards, JSON-LD, alternate languages, RSS feeds */
  safari_extract_meta: Record<string, never>;
  /** Extract HTML tables as structured JSON (headers + rows). Perfect for scraping data tables. */
  safari_extract_tables: {
    /** CSS selector (default: 'table') */
    selector?: string;
    /** Max tables (default: 10) */
    limit?: number;
  };
  /** Fill/replace value in an input, textarea, select, OR contenteditable (rich text). Handles React controlled inputs, ProseMirror, Draft.js, and Google Closure editors automatically. Use for SETTING a value (replaces existing). For code editors (Monaco/CodeMirror/Ace), use safari_replace_editor instead. For character-by-character typing in search boxes, use safari_type_text. IMPORTANT: When using ref, always take a FRESH safari_snapshot first — refs expire after each new snapshot (prefix changes: 5_xx → 6_xx). */
  safari_fill: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** Ref ID from safari_snapshot */
    ref?: string;
    /** CSS selector */
    selector?: string;
    /** Value to fill */
    value: string;
  };
  /** Fill a form AND submit it in one operation. Finds submit button automatically if not specified. */
  safari_fill_and_submit: {
    /** Fields to fill */
    fields: {
      /** CSS selector */
      selector: string;
      /** Value to fill */
      value: string;
    }[];
    /** Submit button selector (auto-detected if omitted) */
    submitSelector?: string;
  };
  /** Fill multiple form fields at once */
  safari_fill_form: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** Array of {selector, value} pairs */
    fields: {
      /** CSS selector */
      selector: string;
      /** Value to fill */
      value: string;
    }[];
  };
  /** Get computed CSS styles for an element. Optionally filter specific properties. */
  safari_get_computed_style: {
    /** CSS selector */
    selector: string;
    /** Specific CSS properties to get (e.g. ['color', 'font-size']) */
    properties?: string[];
  };
  /** Get captured console messages (must call safari_start_console first) */
  safari_get_console: Record<string, never>;
  /** Get cookies for the current page */
  safari_get_cookies: Record<string, never>;
  /** Get detailed info about an element (tag, text, rect, attributes, visibility) */
  safari_get_element: {
    /** CSS selector */
    selector: string;
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
  };
  /** Read records from an IndexedDB database store */
  safari_get_indexed_db: {
    /** Database name */
    dbName: string;
    /** Object store name */
    storeName: string;
    /** Max records (default: 20) */
    limit?: number;
  };
  /** Get HTML source of current page */
  safari_get_source: {
    /** Max chars (default: 200000) */
    maxLength?: number;
  };
  /** Go back in browser history */
  safari_go_back: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
  };
  /** Go forward in browser history */
  safari_go_forward: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
  };
  /** Set up handler for the next alert/confirm/prompt dialog */
  safari_handle_dialog: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** Accept or dismiss (default: accept) */
    action?: "accept" | "dismiss";
    /** Text to enter for prompt dialogs */
    text?: string;
  };
  /** Hover over element. Use ref, selector, or x/y */
  safari_hover: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** Ref ID from safari_snapshot */
    ref?: string;
    /** CSS selector */
    selector?: string;
    /** X coordinate */
    x?: number;
    /** Y coordinate */
    y?: number;
  };
  /** Import storage state from JSON (as exported by safari_export_storage) — restores cookies, localStorage, sessionStorage */
  safari_import_storage: {
    /** JSON string from safari_export_storage */
    state: string;
  };
  /** Validate the page's <meta name=viewport> against iOS Safari best practices: width=device-width, initial-scale, disabled-zoom (WCAG 1.4.4), viewport-fit=cover. Returns parsed attributes + severity-tagged issues (error/warning/info). */
  safari_inspect_viewport: Record<string, never>;
  /** List every document in the tab — the main page plus each iframe — with its frameId, URL and text length. Use when a page's content lives in a cross-origin iframe (an embedded app, a micro-frontend shell, a payment field): safari_read_page and safari_evaluate see only the main document there and come back empty or with a loader. Pass the frameId or a URL substring as safari_evaluate's `frame` to run inside it. */
  safari_list_frames: {
    /** Opaque extension-issued tab receipt */
    receipt?: string;
  };
  /** List all IndexedDB databases on the current page */
  safari_list_indexed_dbs: Record<string, never>;
  /** List every tab in this session's Safari window (titles + URLs, including the user's own tabs — verbose and rarely needed). Tabs this session owns carry a receipt. Prefer keeping the receipt from safari_new_tab over listing. */
  safari_list_tabs: Record<string, never>;
  /** Get localStorage data for the current page */
  safari_local_storage: {
    /** Specific key to get (omit for all) */
    key?: string;
  };
  /** Intercept network requests matching a URL pattern and return a mock response. Works with both fetch and XHR. Useful for testing API error states, offline behavior, or replacing API responses. */
  safari_mock_route: {
    /** URL substring or regex pattern to match (e.g. '/api/users' or 'example\.com') */
    urlPattern: string;
    /** Mock response to return */
    response: {
      /** HTTP status code (default: 200) */
      status?: number;
      /** Response body string (JSON, HTML, text) */
      body?: string;
      /** Content-Type header (default: application/json) */
      contentType?: string;
    };
  };
  /** OS-level mouse click via macOS CGEvent — produces isTrusted: true events that pass WAF/bot detection (G2, Cloudflare, etc.). Use when regular safari_click fails with 405/403 errors or form submissions are blocked. Trade-off: physically moves the mouse cursor and requires Safari window to be visible. Use ref (from snapshot), selector, text, or x/y. When using ref, always take a FRESH safari_snapshot first. */
  safari_native_click: {
    /** Ref ID from safari_snapshot (e.g. '0_5') */
    ref?: string;
    /** CSS selector */
    selector?: string;
    /** Visible text to find and click */
    text?: string;
    /** Viewport X coordinate */
    x?: number;
    /** Viewport Y coordinate */
    y?: number;
    /** Double-click instead of single click */
    doubleClick?: boolean;
    /** auto (default): mouse click, and if the page saw no trusted mouse event (macOS 26 filters them) focus the element and press Space/Return natively. mouse: mouse only. keyboard: skip the mouse, focus + native key (needs ref/selector/text). */
    activate?: "auto" | "mouse" | "keyboard";
  };
  /** OS-level mouse hover via macOS CGEvent — moves the real cursor to an element to trigger native :hover / mouseenter handlers. Use for obfuscated UIs where JS-dispatched mouseenter isn't enough, like Discord server sidebars (tooltips only appear on real hover) or portal-rendered tooltips. After hover, call safari_wait_for or safari_evaluate to read the tooltip. Dwells for dwellMs to let tooltips render, then restores the original cursor position by default. Requires Safari window to be visible. */
  safari_native_hover: {
    /** Ref ID from safari_snapshot */
    ref?: string;
    /** CSS selector */
    selector?: string;
    /** Visible text to find and hover */
    text?: string;
    /** Viewport X coordinate */
    x?: number;
    /** Viewport Y coordinate */
    y?: number;
    /** Milliseconds to dwell over the element so tooltips render (clamped 0-5000) */
    dwellMs?: number;
    /** Restore cursor to original position after dwell */
    restoreMouse?: boolean;
  };
  /** OS-level keyboard event via macOS CGEvent — sends a real keypress (with optional modifiers) to the Safari window WITHOUT activating Safari or stealing focus. Use when safari_press_key's JS path doesn't reach React trust-gated handlers (Discord ProseMirror Enter, Slack send, virtualized editors). Keys: enter, return, tab, escape, space, delete, backspace, up/down/left/right, home, end, pageup, pagedown, f1-f6, a-z, 0-9 and common punctuation. Modifiers: cmd, shift, alt, ctrl. Produces isTrusted:true events. Never activates Safari — runs entirely in the background. */
  safari_native_keyboard: {
    /** Key name: enter, escape, tab, space, arrow keys, letters, digits, etc. */
    key: string;
    /** Modifier keys: cmd, shift, alt, ctrl */
    modifiers?: string[];
  };
  /** Insert text into ANY editor via OS-level clipboard paste (CGEvent Cmd+V targeted to Safari window). Unlike safari_fill which manipulates DOM directly (breaking React/ProseMirror state), this goes through the real paste pipeline — ProseMirror/Slate/Draft.js process the paste event natively and update their internal model. After native_type, pressing Enter (via safari_native_keyboard) will actually submit the form because the framework state matches the DOM. Saves and restores the user's clipboard. No focus stealing. Use for Discord, Slack, and any editor where safari_fill works visually but the content isn't 'really there' when you try to submit. */
  safari_native_type: {
    /** Text to insert via clipboard paste */
    value: string;
    /** CSS selector of the editor element to focus first */
    selector?: string;
    /** Ref ID from safari_snapshot to focus first */
    ref?: string;
  };
  /** Navigate this session's tab to a URL (pass `receipt` to pin the tab). Waits for the page to load. Returns {title, url} — plus a fresh `receipt` when the origin changed; use that one from then on. */
  safari_navigate: {
    /** URL to navigate to */
    url: string;
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
  };
  /** Navigate to a URL and return the page content in one step — saves 1 full round-trip vs navigate+read_page. Use instead of safari_navigate + safari_read_page. */
  safari_navigate_and_read: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** URL to navigate to */
    url: string;
    /** Max chars to return (default: 50000) */
    maxLength?: number;
    /** Load timeout in ms (default: 30000) */
    timeout?: number;
  };
  /** Quick network overview via Performance API (no setup needed). Shows URLs and timing for resources loaded by the page. For detailed request/response info (headers, status codes, POST bodies), use safari_start_network_capture + safari_network_details instead. */
  safari_network: {
    /** Max requests to return (default: 50) */
    limit?: number;
  };
  /** Get captured network requests with full details (must call safari_start_network_capture first) */
  safari_network_details: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** Max requests (default: 50) */
    limit?: number;
    /** Filter by URL substring */
    filter?: string;
  };
  /** Open a new background tab (never steals focus), optionally with a URL. Returns {tabIndex, safeUrl, receipt}. KEEP THE RECEIPT and pass it as `receipt` to every later call on this tab — it survives MCP reconnects, daemon restarts, parallel sessions and subagents, and makes safari_list_tabs / safari_switch_tab unnecessary. */
  safari_new_tab: {
    /** URL to open (empty for blank tab) */
    url?: string;
  };
  /** Override the browser's geolocation API to return custom coordinates */
  safari_override_geolocation: {
    /** Latitude (-90 to 90) */
    latitude: number;
    /** Longitude (-180 to 180) */
    longitude: number;
    /** Accuracy in meters (default: 100) */
    accuracy?: number;
  };
  /** Paste an image from a local file into the focused element via JS DataTransfer (no clipboard, no focus steal). Works on Medium, dev.to, HackerNoon, TOI, etc. */
  safari_paste_image: {
    /** Absolute path to the image file (PNG, JPG, WebP) */
    filePath: string;
  };
  /** Get detailed performance metrics: navigation timing, Web Vitals (FCP, LCP, CLS), resource breakdown, memory usage */
  safari_performance_metrics: Record<string, never>;
  /** Press a keyboard key (enter, tab, escape, arrows, etc). Supports modifiers (cmd, shift, alt, ctrl). */
  safari_press_key: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** Key name: enter, tab, escape, space, delete, up, down, left, right, or a single character */
    key: string;
    /** Modifier keys: cmd, shift, alt, ctrl */
    modifiers?: string[];
  };
  /** Find all elements matching a CSS selector (returns tag, text, href, value). x/y are relative to each element's own frame viewport — for matches inside an iframe, click by selector or snapshot ref, not by these coordinates */
  safari_query_all: {
    /** CSS selector */
    selector: string;
    /** Max results (default: 20) */
    limit?: number;
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
  };
  /** List available options of a react-select v5 dropdown without opening the menu. Returns JSON {ok, total, options:[{label,value}…]}. Useful when safari_react_select_set returns 'option not found' and you need to see exact labels (e.g. 'Email Routing Rules' vs 'Email Routing'). Either ref or selector required. */
  safari_react_select_list_options: {
    /** CSS selector */
    selector?: string;
    /** Ref ID from safari_snapshot */
    ref?: string;
  };
  /** Set a value in a react-select v5 dropdown by walking React fiber to find the Select component and invoking onChange directly — bypasses the menu UI entirely. Use when safari_click on the chevron or option keeps failing (Cloudflare custom token forms after a few rows, portal-rendered selects that intercept synthetic events). Returns JSON {ok, selected} on success, or {ok:false, error, available:[…]} listing up to 30 option labels on miss. Match is by label, value, or case-insensitive label. Either ref or selector required. NOTE: For Permissions-levels combos that are disabled until a Permission is selected, set the Permissions value first — the level combo becomes enabled and its props.options populate. */
  safari_react_select_set: {
    /** CSS selector — typically input[name=...] or the .react-select__control container */
    selector?: string;
    /** Ref ID from safari_snapshot */
    ref?: string;
    /** Option label (or value) to select — case-insensitive fallback */
    value: string;
  };
  /** Read page text content (title, URL, body text). Use for reading article text or page content. For interacting with elements, prefer safari_snapshot (gives ref IDs). Use selector to read specific element. Use maxLength to limit output. */
  safari_read_page: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** CSS selector to read specific element */
    selector?: string;
    /** Max chars to return (default: 50000) */
    maxLength?: number;
  };
  /** Reload the current page */
  safari_reload: {
    /** Hard reload (bypass cache) */
    hard?: boolean;
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
  };
  /** Hot-reload the Safari MCP Bridge extension — forces it to reload its own code from disk without requiring manual Safari Preferences → Extensions → toggle. Use after editing extension/background.js or extension/content.js in the safari-mcp repo. The extension briefly disconnects during reload and auto-reconnects within ~2 seconds. NOTE: this tool itself requires the extension version already installed to support the `reload_extension` command (added in v2.9.1+). If your extension is older, trigger a manual reload once to pick up this feature. */
  safari_reload_extension: Record<string, never>;
  /** Replace ALL content in a code editor (Monaco, CodeMirror, Ace, ProseMirror). Use ONLY for code editors — Airtable automations, GitHub gists, CodePen, n8n code nodes, etc. NOT for rich text editors like Medium/LinkedIn (use safari_fill for those). Detects ProseMirror/Draft.js/CodeMirror/Monaco/Ace and uses their native API. */
  safari_replace_editor: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** The complete code/text to put in the editor */
    text: string;
  };
  /** Reset device emulation: restores the window size from before safari_emulate and removes its navigator overrides (no reload) */
  safari_reset_emulation: Record<string, never>;
  /** Resize the Safari window */
  safari_resize: {
    /** Window width */
    width: number;
    /** Window height */
    height: number;
  };
  /** Right-click (context menu) an element by CSS selector or x/y coordinates */
  safari_right_click: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** CSS selector */
    selector?: string;
    /** X coordinate */
    x?: number;
    /** Y coordinate */
    y?: number;
  };
  /** Batch Safari actions in one MCP session. Named profiles use the verified extension and support: newTab, switchTab, getReceipt, listTabs, closeTab, navigate, navigateAndRead, readPage, snapshot, getElementInfo, querySelectorAll, waitFor, waitForTime, click, clickAndOpenPopup, fill, fillForm, clearField, typeText, selectOption, pressKey, scroll, scrollTo, scrollToElement, hover, evaluate, reload, goBack, goForward. switchTab accepts an index or an opaque receipt; a valid receipt recovers the exact owned tab across Safari windows without focusing one. clickAndOpenPopup takes exactly one selector or snapshot ref, targets one exact frame, performs one click, captures a blocked HTTP(S) window.open, and opens it as a background tab without focusing Safari; it refuses CAPTCHA/challenge targets and never returns URL query/hash data. Non-profile mode retains the legacy action set. Use getReceipt after a cross-origin redirect. */
  safari_run_script: {
    /** Array of steps to execute sequentially */
    steps: {
      /** Action name (e.g. 'navigate', 'click', 'fill') */
      action: string;
      /** Arguments for the action */
      args?: Record<string, unknown>;
    }[];
  };
  /** Read the live CSS safe-area-inset values (top/right/bottom/left) as the page sees them, whether viewport-fit=cover is set, and whether env(safe-area-inset-*) is used in any stylesheet. For notch / Dynamic Island layout debugging. */
  safari_safe_area_insets: Record<string, never>;
  /** Save the current page as a PDF file. Uses screencapture + PDF rendering (no Safari UI interaction needed). */
  safari_save_pdf: {
    /** Absolute file path to save the PDF (e.g. /Users/am/Downloads/page.pdf) */
    path: string;
  };
  /** Take a visual screenshot (base64 JPEG). EXPENSIVE — use safari_snapshot instead for most tasks. Only use screenshot when you need to verify visual layout, styling, images, or colors that snapshot can't show. Pass maxWidth (e.g. 1024) for layout checks — far fewer tokens. */
  safari_screenshot: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** Capture full page (not just viewport) */
    fullPage?: boolean;
    /** Downscale to this pixel width before returning (default: env SAFARI_MCP_SCREENSHOT_MAX_WIDTH, else none). Retina captures are 2× the viewport; 1280 keeps text readable at a third fewer tokens, 800 is plenty for layout checks. 0 = never scale. */
    maxWidth?: number;
  };
  /** Take a screenshot of a specific element (by CSS selector). Returns a base64 image. */
  safari_screenshot_element: {
    /** CSS selector of the element to capture */
    selector: string;
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
  };
  /** Scroll the page up or down by a specified amount */
  safari_scroll: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** Scroll direction (default: down) */
    direction?: "up" | "down";
    /** Pixels to scroll (default: 500) */
    amount?: number;
  };
  /** Scroll to a specific position on the page */
  safari_scroll_to: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** X position (default: 0) */
    x?: number;
    /** Y position (default: 0) */
    y?: number;
  };
  /** Scroll to element by CSS selector OR text. For virtual DOM (Airtable) use text — scrolls down until text appears in DOM. */
  safari_scroll_to_element: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** CSS selector of target element */
    selector?: string;
    /** Text to find — scrolls down until it appears (for virtual DOM/lazy loading) */
    text?: string;
    /** Scroll alignment (default: center) */
    block?: "start" | "center" | "end" | "nearest";
    /** Max time to scroll in ms (default: 10000) */
    timeout?: number;
  };
  /** Select an option in a native <select> dropdown. Sets .value and dispatches change event. Pass `ref` (from safari_snapshot) for a select inside an iframe or shadow DOM — a plain `selector` only reaches the top document. For custom dropdowns (React/LinkedIn), use safari_click on the dropdown trigger, then safari_click on the option instead. */
  safari_select_option: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** CSS selector of the select (top document only) */
    selector?: string;
    /** Ref ID from safari_snapshot — required for selects inside iframes/shadow DOM */
    ref?: string;
    /** Option value or visible label to select */
    value: string;
  };
  /** Get sessionStorage data for the current page */
  safari_session_storage: {
    /** Specific key (omit for all) */
    key?: string;
  };
  /** Set a cookie on the current page */
  safari_set_cookie: {
    /** Cookie name */
    name: string;
    /** Cookie value */
    value: string;
    /** Cookie domain */
    domain?: string;
    /** Cookie path (default: /) */
    path?: string;
    /** Expiry date (e.g. 'Thu, 01 Jan 2030 00:00:00 GMT') */
    expires?: string;
    /** Secure flag */
    secure?: boolean;
    /** SameSite attribute */
    sameSite?: "Strict" | "Lax" | "None";
  };
  /** Set a value in localStorage */
  safari_set_local_storage: {
    /** Storage key */
    key: string;
    /** Value to store */
    value: string;
  };
  /** Set a value in sessionStorage */
  safari_set_session_storage: {
    /** Storage key */
    key: string;
    /** Value to store */
    value: string;
  };
  /** PREFERRED way to see page state. Returns accessibility tree with ref IDs for every interactive element. Use refs with click/fill/type instead of CSS selectors. Workflow: snapshot → see refs → click({ref:'0_5'}). PREFER THIS over safari_screenshot (cheaper, structured text vs heavy image) and over safari_read_page (includes interactive refs). Use safari_screenshot only when you need to see visual layout/styling. */
  safari_snapshot: {
    /** CSS selector for subtree (default: full page) */
    selector?: string;
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
  };
  /** Start capturing console messages (log, warn, error, info). Call once per page. */
  safari_start_console: Record<string, never>;
  /** Start capturing detailed network requests (fetch + XHR) with headers, status, timing. Call once per page. Intercepts fetch/XHR — captures requests AFTER this call only. For quick overview of already-loaded resources, use safari_network instead. */
  safari_start_network_capture: Record<string, never>;
  /** Switch the MCP session's logical target without focusing Safari. Pass an index for the current session window, or an opaque receipt to recover the exact owned tab across Safari windows; a valid receipt takes precedence over any supplied index. Rarely needed: passing `receipt` on each tool call already targets that tab. */
  safari_switch_tab: {
    /** Tab index (starting from 1); optional when receipt is provided */
    index?: number;
    /** Opaque extension-issued receipt for the exact owned tab */
    receipt?: string;
    /** Deprecated legacy receipt URL */
    url?: string;
  };
  /** Simulate slow network conditions. Profiles: slow-3g, fast-3g, 4g, offline. Or custom latency/speed. Call with no args to reset. */
  safari_throttle_network: {
    /** Preset: slow-3g, fast-3g, 4g, offline */
    profile?: string;
    /** Custom latency in ms */
    latency?: number;
    /** Custom download speed in Kbps */
    downloadKbps?: number;
  };
  /** Type text character-by-character with realistic key events. Best for: search boxes (triggers autocomplete), chat inputs, and fields that react to each keystroke. For rich text editors (Medium, HackerNoon, LinkedIn), use safari_fill instead — it uses framework-native APIs. For code editors (Monaco/CodeMirror), use safari_replace_editor. When using ref, always take a FRESH safari_snapshot first — refs expire after each new snapshot. */
  safari_type_text: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** Text to type */
    text: string;
    /** Ref ID from safari_snapshot */
    ref?: string;
    /** CSS selector to focus */
    selector?: string;
  };
  /** Upload a file to a <input type='file'> element via JavaScript DataTransfer — NO file dialog, NO UI interaction. IMPORTANT: Do NOT click the file input before calling this tool — just provide the selector and file path. If a file dialog is already open, this tool will close it first. NOTE: 'verified 0 files' may appear even on success if the site uses a custom upload handler — check visually with safari_snapshot. For an IMAGE going into a composer/editor that should show a thumbnail, pass verifyPreview:true — some sites (Google Business Profile) accept the file handle and flip their UI to 'attached' while ingesting nothing, and the post then publishes with no image. */
  safari_upload_file: {
    /** CSS selector of the file input */
    selector: string;
    /** Absolute path to the file to upload */
    filePath: string;
    /** Require a visible preview (blob:/data: image) to appear; if none does, the synthetic pickup was a ghost and this escalates to a real OS file dialog. Use for images going into a composer. */
    verifyPreview?: boolean;
    /** Skip synthetic injection and go straight to the real OS file dialog (isTrusted). Needs an unlocked screen and briefly focuses Safari. Use when the site is known to reject synthetic uploads. */
    forceNative?: boolean;
  };
  /** Verify the framework-level state of an editor/input matches the expected value. Returns JSON {match, mode, actual, expected, hint?}. Modern editors (ProseMirror, Lexical, Closure, React-controlled inputs) maintain state separately from the DOM — `.value` or `.textContent` may show new text while the internal store still holds old data, so a Submit click sends stale data. Call this AFTER safari_fill and BEFORE clicking Submit on critical forms (Featured.com, LinkedIn share, Medium, Reddit). */
  safari_verify_state: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** CSS selector of the editor/input to verify */
    selector: string;
    /** Expected value or text fragment that should appear in framework state */
    expected: string;
  };
  /** Wait for a fixed time in milliseconds. Use only when you need a brief pause between actions. PREFER safari_wait_for (waits for element/text to appear) — it's smarter and doesn't waste time. */
  safari_wait: {
    /** Milliseconds to wait */
    ms: number;
  };
  /** Wait for an element or text to appear on the page */
  safari_wait_for: {
    /** Tab receipt from safari_new_tab — pins this call to that tab (survives reconnects/subagents) */
    receipt?: string;
    /** CSS selector to wait for */
    selector?: string;
    /** Text to wait for */
    text?: string;
    /** Timeout in ms (default: 10000) */
    timeout?: number;
  };
  /** Wait for a new tab to appear (e.g. after OAuth login click opens popup). Automatically switches to the new tab. */
  safari_wait_for_new_tab: {
    /** Timeout in ms (default: 10000) */
    timeout?: number;
    /** Only match new tabs whose URL contains this string */
    urlContains?: string;
  };
  /** Check every CSS property used on the page against THIS Safari via CSS.supports() — reports unsupported properties, properties that need a -webkit- prefix, and known Safari rendering quirks (e.g. position:sticky inside overflow ancestors). Tested in the live engine, so no false positives. */
  safari_webkit_compat: Record<string, never>;
}

export type SafariToolName = keyof SafariToolInputs;
export type SafariToolInput<N extends SafariToolName> = SafariToolInputs[N];

/** With SAFARI_MCP_LANES=1 every tool additionally requires a laneId. */
export type SafariLaneToolInput<N extends SafariToolName> = SafariToolInputs[N] & { laneId: string };

/** Through the profile router (safari-mcp-profiles) every tool also takes an optional safariProfile. */
export type SafariProfileToolInput<N extends SafariToolName> = SafariToolInputs[N] & { safariProfile?: string };

export declare const SAFARI_TOOL_COUNT: 98;
