#!/usr/bin/env node
// Generates index.d.ts from the server's own tool registrations.
//
// A hand-written declaration file was proposed upstream (83 tools) and would have been wrong
// by the time it merged: the server registers 98 today, and the tool count has drifted from
// the docs three times already (see test/doc-tool-count.test.mjs). So the types are derived
// from what `tools/list` actually returns, and test/types-generated.test.mjs fails when the
// committed file no longer matches. Regenerate with:  npm run gen:types
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

export async function listTools() {
  const transport = new StdioClientTransport({
    command: process.execPath,
    args: ["index.js"],
    cwd: ROOT,
    // Lanes off: the base schemas are what we describe; laneId is added as a mapped type.
    env: { ...process.env, SAFARI_MCP_QUIET: "1", SAFARI_MCP_LANES: "", SAFARI_MCP_HTTP: "" },
    stderr: "pipe",
  });
  const client = new Client({ name: "safari-mcp-gen-types", version: "0.0.0" });
  try {
    await client.connect(transport, { timeout: 15_000 });
    const { tools } = await client.listTools(undefined, { timeout: 15_000 });
    return tools;
  } finally {
    await client.close().catch(() => {});
    await transport.close().catch(() => {});
  }
}

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const key = (k) => (IDENT.test(k) ? k : JSON.stringify(k));

// JSON Schema (as emitted by the SDK from zod) -> TypeScript type expression.
export function toTs(schema, indent = "") {
  if (!schema || typeof schema !== "object") return "unknown";
  if (Array.isArray(schema.enum)) return schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  if ("const" in schema) return JSON.stringify(schema.const);
  const union = schema.anyOf || schema.oneOf;
  if (Array.isArray(union)) return [...new Set(union.map((s) => toTs(s, indent)))].join(" | ");
  if (Array.isArray(schema.type)) return schema.type.map((t) => toTs({ ...schema, type: t }, indent)).join(" | ");
  switch (schema.type) {
    case "string": return "string";
    case "number":
    case "integer": return "number";
    case "boolean": return "boolean";
    case "null": return "null";
    case "array": {
      const item = toTs(schema.items, indent);
      return /[|&]/.test(item) ? `Array<${item}>` : `${item}[]`;
    }
    case "object": return objectType(schema, indent);
    default: return "unknown";
  }
}

function objectType(schema, indent) {
  const props = schema.properties || {};
  const names = Object.keys(props);
  const extra = schema.additionalProperties;
  if (!names.length) {
    if (extra && typeof extra === "object") return `Record<string, ${toTs(extra, indent)}>`;
    return "Record<string, never>";
  }
  const required = new Set(schema.required || []);
  const inner = indent + "  ";
  const lines = names.map((n) => {
    const p = props[n];
    const doc = p && p.description ? `${inner}/** ${oneLine(p.description)} */\n` : "";
    return `${doc}${inner}${key(n)}${required.has(n) ? "" : "?"}: ${toTs(p, inner)};`;
  });
  return `{\n${lines.join("\n")}\n${indent}}`;
}

const oneLine = (s) => String(s).replace(/\s+/g, " ").replace(/\*\//g, "*\\/").trim();

export function renderTypes(tools) {
  const sorted = [...tools].sort((a, b) => a.name.localeCompare(b.name));
  const entries = sorted.map((t) => {
    const doc = t.description ? `  /** ${oneLine(t.description)} */\n` : "";
    return `${doc}  ${key(t.name)}: ${toTs({ type: "object", ...t.inputSchema }, "  ")};`;
  });
  return `// GENERATED by scripts/gen-types.mjs from the server's tools/list — do not edit.
// Regenerate with \`npm run gen:types\`; test/types-generated.test.mjs fails on drift.
//
// Input types for every safari-mcp tool (${sorted.length}), for TypeScript MCP clients:
//   const args: SafariToolInput<"safari_navigate"> = { url: "https://example.com" };
//   await client.callTool({ name: "safari_navigate", arguments: args });

export type MCPContent =
  | { type: "text"; text: string }
  | { type: "image"; data: string; mimeType: string };

export interface MCPToolResult {
  content: MCPContent[];
  isError?: boolean;
}

export interface SafariToolInputs {
${entries.join("\n")}
}

export type SafariToolName = keyof SafariToolInputs;
export type SafariToolInput<N extends SafariToolName> = SafariToolInputs[N];

/** With SAFARI_MCP_LANES=1 every tool additionally requires a laneId. */
export type SafariLaneToolInput<N extends SafariToolName> = SafariToolInputs[N] & { laneId: string };

export declare const SAFARI_TOOL_COUNT: ${sorted.length};
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const out = renderTypes(await listTools());
  writeFileSync(join(ROOT, "index.d.ts"), out);
  console.log(`index.d.ts written (${out.split("\n").length} lines)`);
}
